version: "3"
services:
  json-server:
    container_name: json-server
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./services/kota-shop-management-system/db/db.json:/usr/src/app/db.json
    command: ["json-server", "--watch", "db.json", "--port", "3000"]
