version: "3"
services:

  local-db:
    container_name: local-db
    image: postgres:14-alpine
    # build:
    #   context: ./services/lw_api/db
    #   dockerfile: db.dockerfile
    ports:
      - 5433:5432
    volumes:
      - local-db-data:/var/lib/postgresql/data/pgdata
      # - ./services/lw_api/db/sql:/docker-entrypoint-initdb.d/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c log_statement=all

  db-local:
    container_name: db-local
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=_db
    volumes:
      - db-local-data:/var/lib/postgresql/data/pgdata
    command: postgres -c log_statement=all

  cloudsql-proxy:
    # access your cloud sql database from your local machine
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    ports:
      - 5432:5432
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/config
    restart: always
    command: /cloud_sql_proxy --dir=/cloudsql -instances=quick-desk-2:europe-west1:quick-desk-sql-instance=tcp:0.0.0.0:5432 -credential_file=/config

  redis:
    container_name: redis
    image: redis:alpine
    # environment:
    # - REDIS_PASSWORD=ubuntu
    # - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server

  redisinsight:
    # redis db visualization dashboard
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

  pgadmin:
    # postgres database graphical interface dashboard
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=grespost
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    # environment:
      # - GF_DATABASE_TYPE=postgres
      # - GF_DATABASE_URL=postgres://postgres:?6[T5FHl_Ky|Q>yL@local-db:5432/grafana
      # - GF_DATABASE_SSL_MODE=disable
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  local-db-data:
  redis-data:
  redisinsight:
  db-local-data:
  pgadmin-data:
  grafana-data:
