version: "3"
services:
  kota-shop_frontend:
    container_name: kota-shop_frontend
    build:
      context: ./services/kota-shop-management-system/frontend
      dockerfile: frontend.dockerfile  # Ensure this file exists
    ports:
      - 4200:4200
    volumes:
      - ./services/kota-shop-management-system/frontend/app:/home/node/app
    command: "yarn start --host 0.0.0.0"

  kota-shop_backend:
    container_name: kota-shop_backend
    build:
      context: ./services/kota-shop-management-system/backend
      dockerfile: backend.dockerfile  # Ensure this file exists
    ports:
      - "8080:8080"
    volumes:
      - ./services/kota-shop-management-system/backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:masterKey@db:5432/database_aws
    command: ["go", "run", "main.go"]

  local-db:
    container_name: local-db
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - local-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masterKey
    command: postgres -c log_statement=all

  db-local:
    container_name: db-local
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masterKey
      - POSTGRES_DB=_db
    volumes:
      - db-local-data:/var/lib/postgresql/data/pgdata
    command: postgres -c log_statement=all

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=grespost
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local-db-data:
  db-local-data:
  pgadmin-data:
