version: "3"
services:

  kota-shop_frontend:
    container_name: kota-shop_frontend
    build:
      context: ./services/kota-shop/frontend
      dockerfile: frontend.dockerfile
      network: host
    ports:
      - 4200:4200
    volumes:
      - ./services/kota-shop/frontend/app:/home/node/app
    command: "yarn start --host 0.0.0.0"

    
  json-server:
    container_name: json-server
    image: json-server:latest
    ports:
      - 3000:3000
    volumes:
      - ./path/to/db.json:/usr/src/app/db.json
    command: "json-server --watch /usr/src/app/db.json --port 3000"