name: Deploy to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Docker
      run: sudo apt-get install -y docker.io

    - name: Build Docker image
      run: docker build -f services/kota-shop-management-system/server.dockerfile -t my-image .

    - name: Deploy to S3
      uses: aws-actions/s3-sync-action@v1
      with:
        source-dir: 'build'
        destination-bucket: 'sam2awsbucket'
        args: '--acl public-read --delete'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
