name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'  # Specify the Go version you need

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'  # Updated to the required Node.js version

      - name: Install dependencies and build backend
        run: |
          cd services/kota_shop/go_backend
          go mod tidy
          go build -o kota_shop_backend main.go

      - name: Install dependencies and build frontend
        run: |
          cd services/kota_shop/frontend/app/
          yarn install
          yarn ng build --configuration production --aot

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync services/kota_shop/frontend/app/dist/ s3://sam2awsbucket --delete
